### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by gloriaodipo**
This pull request seeks to merge develop branch into master, having done all the necessary tasks. It includes: user **signup and login** endpoints, endpoints to **add an entry, get a single entry, get all entries, delete an entry and modify an entry.** It also has continuous integration implemented and the app is hosted on heroku.

### CODE REVIEW

**Comment by dmithamo** [comment]
Hey @gloriaodipo ,
I think you should have written up a description for the PR, to make it clear what the code accomplishes, so that a reviewer knows what to look out for. :/

**Comment by SrMoffat** [comment]
Wow....you have done so much already. This is a challenge. Good job and awesome pace.

**Comment by charisschomba** [comment]
Nice work gloria

**Comment by inventiphGuru** [comment]
noting that you have done all the above, have you created tests for the responses for the Api?

**Comment by gloriaodipo** [comment]
@inventiphGuru take a look at my tests folder

**Pull request merged**
